package com.hclc.kafkainspring.integrationtests;

public enum TypeOfFailure {
    EXCEPTION_AFTER_CONSUMED, EXCEPTION_AFTER_FORWARDED, EXCEPTION_BEFORE_DB_COMMIT, EXCEPTION_AFTER_DB_COMMIT, PROCESSING_TIME_EXCEEDING_SESSION_TIMEOUT, NONE
}
